apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: us.icr.io/sn-labs-pakoujuste20/accounts:1
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-name
        - name: DATABASE_URI
          value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@postgresql:5432/$(DATABASE_NAME)"
        command: ["/bin/sh", "-c"]
        args:
          - export DATABASE_URI="postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@postgresql:5432/$(DATABASE_NAME)";
            exec gunicorn --bind=0.0.0.0:8080 --log-level=info service:app