apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: accounts
    app.kubernetes.io/component: account-service
  name: accounts
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: accounts
  type: ClusterIP
status:
  loadBalancer: {}
